language : bash
script :
  - bash ./deploy.sh
env:
  global:
    secure: EwNR7BR+UdlZeYweLbT4k2mShsf68bbrwSuY1Jl4mXsB0nfw/jNoX4bNAOoeUOFjsh109w8R3E5hMIgfosELq6dnkjag2eyClKLjd2foBiKyCa8xu9Q81lE+J7IXtjEwAShozZslTX3zv4cMH2DVQn+8OkADBWueIgFItbi5mtJ5AvWNJStS9rxqyPCINf6eT/1olmJPDRWe8VrS1kQ8l4qh55no1+BZXtpZT2MgCbr8mIbhSrec3wIPLOs2H609fARoJNXl5a8nR+U4chenfV4Q8C0sFo7lEmfp673HyEcW9fFMXkbzqHgmWMUq+IQZeUCppYjoorgjGiSYTwxBVR3GhQAZHM0tnkpF+pOkrI+W05xJh/oz6I2aiKIF6bD8TVloPVMcH7Kgj0Gy37qNcmF1rnkGq22azQVf/aElaymf6dBuq+Ospy7WGlm/lMdbbc6RXS2djQ3CqcRy9HpNMMwmjrgDs8juE4iIhpG9HTHRSj9BzE8kt9iqAK53tirVp0wS40xPlWs1PlgdVfmsX9/eNbvLMLh4v5kkLOXTUgQ9oi7bfikGh+mZYK8vC32szrvXnEXOd7KVoFKbjrAWHQu5zvJSn2Ev0+hQLXfjDYF8XMRkSibKviiUwQLY1NcCOBKPQYkyItrfIHO6jTp0drGOC68hinsEQM15kF1ZfGo=
