title = "Kumano Dormitory IT Section"
baseurl = "https://kumano-dormitory.github.io/"
languageCode = "ja-JP"
theme = "hugo_theme_aglaus"
googleAnalytics = "UA-92377508-1"

[params]
    description = "今まで作成したものや、参加したイベントなどの説明"
